### ISSUE TITLE
Landing Page

### ISSUE THREAD

**Issue by sibelius** [react-brasil/reactconfbr#1]

**Comment by lucasbento** [comment]
Invoco @ronal2do em modo de ataque.

**Comment by alvarowolfx** [comment]
Organizei um Hackathon aqui em Cuiabá e fiz a landing page usando o Gatsby , o que acham para fazer a da ReactConfBR ? Ele gera sites estáticos e usa React.

https://github.com/GovHackMT/conference-site

Posso ajudar também no que precisar.

**Comment by lucasbento** [comment]
@alvarowolfx: podemos sim, o @femontanha usou gatsby no https://github.com/react-brasil/react-brasil-slack também.

**Comment by nic** [comment]
@alvarowolfx Boaaa! Que top cara!!! Podemos sim!

**Comment by lucasbento** [comment]
@alvarowolfx: te convidei pra org, entra no Slack também quando puder: https://react-brasil.github.io/react-brasil-slack/

**Comment by PatriciaMagi** [comment]
Existe um material desenvolvido por uma equipe aqui do SENAI. Caso precisem, estamos por aqui! (11) 3273-5165 e/ou pmagi@sp.senai.br.


**Sites**

_Curso do Desenvolvedor Multiplataforma_
http://informatica.suicobrasileira.com.br/

**Laraconf**
http://laraconfbrasil.com.br/

**E.cub**
https://ecub.sp.senai.br/

[Curso de Android](https://cloud.githubusercontent.com/assets/6439562/22378130/accaade0-e49b-11e6-88b2-daf236ea2879.png)
O site do curso de android está em anexo.

**Comment by danvitoriano** [comment]
landing page no ar ja!
mas continuamos precisando de ajudas e PRs para atualizar as [issues abertas relativas a landing](https://github.com/react-brasil/conf/issues)!
