### ISSUE TITLE
Qual a melhor data para realizar a React Conf no Brasil?

### ISSUE THREAD

**Issue by sibelius** [react-brasil/reactconfbr#11]
Votem com 👍  na data que acharem melhor

Possíveis datas:
```
 16 de Setembro de 2017 (Sábado)
 23 de Setembro de 2017 (Sábado)
 30 de Setembro de 2017 (Sábado)
 07 de Outubro de 2017 (Sábado)
```

---

O evento será em São Paulo/SP.

**Comment by sibelius** [comment]
16 de Setembro de 2017 (Sábado)

**Comment by sibelius** [comment]
23 de Setembro de 2017 (Sábado)

**Comment by sibelius** [comment]
30 de Setembro de 2017 (Sábado)

**Comment by sibelius** [comment]
07 de Outubro de 2017 (Sábado)

**Comment by micuinhomiguel** [comment]
07 de Outubro

**Comment by danvitoriano** [comment]
@micuinhomiguel dá um like na data q vc quer ;)

**Comment by mingomax** [comment]
07 de outubro de 2017 (sábado)

**Comment by danielGalvao** [comment]
São Paulo?

**Comment by mxstbr** [comment]
If it ends up being the 7th of October let me know when the CFP opens, I've always wanted to go to Brazil! :blush:

**Comment by danvitoriano** [comment]
vamos fechar dia 07 de outubro de 2017! 
gonna be october, 07 @mxstbr !
c4p: https://www.papercall.io/reactconfbr

**Comment by mxstbr** [comment]
Yay, that's great! :tada: Submitted some first ideas
