### ISSUE TITLE
Criar codigo de conduta

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/reactconfbr#13]

**Comment by danielGalvao** [comment]
Alguns exemplos para termos um norte para seguir.

http://pt-br.confcodeofconduct.com/

https://braziljs.org/blog/codigo-de-conduta-braziljs-2016/

http://www.thedevelopersconference.com.br/conduta

http://qconsp.com/codigo-de-conduta

https://imasters.com.br/codigo-de-conduta-eventos-imasters/

**Comment by danielGalvao** [comment]
# Código de conduta da _React Conf Brasil 2017_

Todos os participantes, palestrantes, organizadores, patrocinadores e voluntários 
da conferência precisam concordar com este código de conduta. 
Os organizadores vão reforçar que este código seja seguido durante todo o evento. 
Esperamos a cooperação e colaboração de todos os presente no evento, para ajudar a 
garantir um ambiente mais seguro.

## Você ou alguém precisa de ajuda?

Durante o evento, entre em contato com um organizador para solucionar da melhor forma
a sua necessidade.
Você tem os nossos contatos nos emails previamente enviados e livre acesso para nos
contactar.

## Conduta em resumo

A _React Conf Brasil 2017_ é dedicada a fornecer uma experiência de conferência livre de 
assédio para todos, independentemente do sexo, identidade de gênero e expressão,
idade, orientação sexual, deficiência, aparência física, tamanho corporal, cor de pele, 
etnia, religião (ou falta dela) ou escolhas de tecnologias. Nós **NÃO TOLERAMOS** o 
assédio aos participantes da conferência, sob qualquer forma. Linguagem e imagens 
sexuais não são apropriadas em **NENHUM** local da conferência, incluindo palestras, 
workshops, festas, Twitter e outras mídias on-line. Os participantes que violarem
estas regras poderão ser punidos ou expulsos da conferência sem nenhuma restituição, 
a critério dos organizadores da conferência.

## Conduta

Assédio inclui expressões ou comentários verbais ofensivos relacionados ao gênero, identidade 
de gênero e expressão, idade, orientação sexual, deficiência, aparência física, 
tamanho corporal, cor de pele, etnia, religião, escolhas de tecnologias, imagens 
sexuais em espaços públicos, intimidação deliberada, perseguição, stalking, fotografias 
ou filmagens constrangedoras, interrupção contínua das apresentações ou outros eventos, 
contato físico inadequado e atenção sexual indesejada.

Os participantes que receberem uma solicitação para interromper qualquer comportamento 
de assédio devem fazê-lo **IMEDIATAMENTE**.

Os patrocinadores também estão sujeitos às políticas antiassédio. Particularmente, 
os patrocinadores não devem usar imagens, atividades ou outro material de cunho sexual. 
As equipes de estandes e tendas (incluindo voluntários) não devem utilizar roupas, 
uniformes ou trajes sexualizados ou de outra forma criar um ambiente sexualizado.

Se um participante se envolve em comportamento de assédio, os organizadores da 
conferência podem tomar todas as medidas que considerem adequadas, incluindo avisar 
o ofensor ou expulsá-lo da conferência sem nenhum reembolso.

Caso seja assediado, perceba que alguém está sendo assediado ou tenha alguma dúvida, 
entre em contato com um membro da equipe da _React Conf Brasil 2017_ imediatamente. 
Membros da equipe da conferência podem ser identificados pois serão apresentados 
e estarão vestindo camisetas do evento.

A equipe da conferência estará disposta a auxiliar os participantes a contatarem a 
segurança do local, assim como as devidas aplicações da lei local, solicitar a outros
participantes para testemunhar o ocorrido, fornecer escoltas ou ajudar aqueles que 
sofrerem assédio para que se sintam seguros pelo o decorrer da conferência. 
Nós **VALORIZAMOS** a sua participação.

Esperamos que os participantes sigam estas regras em salas de apresentação e 
workshops da conferência, além de eventos sociais relacionados.

## Contato

Qualquer necessidade, dúvida ou outras questões sobre o código de conduta da 
_React Conf Brasil 2017_ entre em contato com a organização. Esse regulamento está
em constante evolução e caso necessário será reestruturado para atender a todos.

reactconfbr@gmail.com

**Comment by danvitoriano** [comment]
Consegue dar um assign pra vc nessa issue @danielGalvao ? 
Vc pode pegar o texto dessas referencias, montar o nosso e postar aqui :)

**Comment by aureliosaraiva** [comment]
@danielGalvao  por que não udamos diretamente o link da braziljs? Não precisamos criar um unicamente nossa, podemos criar usar algo que é comum na comunidade frontend. Clara, desde de que reflitam nossos valores.

**Comment by danvitoriano** [comment]
mas o texto precisa estar no nosso site não @aureliosaraiva ?

**Comment by cyb3113** [comment]
@danielGalvao @danvitoriano  eu escrevi/adaptei o código de conduta do [codamos.club](http://www.codamos.club/C%C3%B3digo%20de%20Conduta%20Codamos.pdf), ele é super abrangente.  vcs querem ajuda? posso adaptar o nosso para vcs!

**Comment by rodrigooler** [comment]
@cyb3113 seria ótimo ter sua ajuda! cc @danvitoriano

**Comment by danvitoriano** [comment]
oi @cyb3113 tudo bem? teria algum problema usarmos o mesmo código?
a gente não usou dos outros lugares pq não tivemos tempo de ir atrás pra perguntar se podíamos!

**Comment by cyb3113** [comment]
@danvitoriano pode usar sim! Eles está sob Creative Commons Attribution 4.0 International License.  Só por favor cite que é do codamos.club   😃

**Comment by danvitoriano** [comment]
poxa @cyb3113 muito obrigado!
galera, problema resolvido! vamos adicionar no código!

**Comment by nic** [comment]
@cyb3113 Muito obrigado querida! \o////

**Comment by danvitoriano** [comment]
published https://github.com/react-brasil/conf/pull/46
