### ISSUE TITLE
Social Media Manager Volunteer

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/reactconfbr#15]
Someone or some company available to help us maintaining social media shares. 

There is no need to write blog posts, only Facebook and Twitter shares to keep community updated.

**All copyrights or credits will be given to the volunteer sponsor**

**Comment by danvitoriano** [comment]
Nossas redes sociais:
- [ ] - [Facebook](https://www.facebook.com/reactconf/)
- [ ] - [Twitter](https://www.twitter.com/reactconfbr)
- [ ] - [Instagram](https://www.instagram.com/reactconfbr/)

Não precisa criar posts de blogs, apenas manter estas 3 redes ativas, divulgando imagens e vídeos feitos por um design, chamando para patrocinar o evento, divulgar venda de ingressos, anunciar novos patrocinadores e palestrantes, e compartilhar as issues abertas no GitHub pedindo ajuda para codar o site ou assuntos de voluntários e organizações.

Os créditos serão colocados no site, ou entra como apoio da Conf.

**Comment by danvitoriano** [comment]
We found her @larissaAbreu welcome on board

**Comment by LarissaAbreu** [comment]
Já quero xD

Posso ajudar com o Twitter e o Insta (o Facebook é meio ruim pra ficar usando no celular e quase não uso ele pelo computador rs)

**Comment by danvitoriano** [comment]
é mais o Twitter mesmo, já estamos alinhados!
