### ISSUE TITLE
Novo visual do site

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/reactconfbr#17]
- [ ] 1 - ser mobile first
- [x] 2 - botão venda de tickets
- [ ] 3 - timeline com speakers, adicionando conforme formos fechando os palestrantes
- [ ] 4 - bio de cada speaker, com contatos das redes sociais
- [x] 5 - links das redes sociais da conf e da comunidade react brasil
- [x] 6 - area com as issues mais votadas do github
- [x] 7 - area ajude o leo a vencer o cancer
- [x] 8 - area sobre a comunidade react brasil
- [ ] 9 - formulario patrocine nosso evento
- [ ] 10 - area com logos dos patrocinadores divididos por cotas
- [ ] 11 - form entre em contato conosco, receba nossos emails
- [ ] 12 - codigo de conduta
- [ ] 13 - link call for papers
- [ ] 14 - links meetups react brasil
- [ ] 15 - download media kit

**Comment by ronal2do** [comment]
Feito com o [Adobe XD](http://www.adobe.com/br/products/experience-design/features.html)
[ReactConf.zip](https://github.com/react-brasil/reactconfbr/files/1106549/ReactConf.zip)
![web 1920 1](https://user-images.githubusercontent.com/4389565/27606427-995ee6f4-5b56-11e7-85a8-9f15ae74794e.png)

**Comment by jgcmarins** [comment]
Sensacional! Parabéns @ronal2do

**Comment by rodrigooler** [comment]
@ronal2do consegue integrar com o https://zeplin.io/ ?

**Comment by ronal2do** [comment]
@rodrigooler O Adobe XD já faz o mesmo trabalho, se precisarem de ajuda para codar isso podem chamar

**Comment by ronal2do** [comment]
http://www.adobe.com/br/products/experience-design/features.html

**Comment by danvitoriano** [comment]
Consegue seguir com isso @rodrigooler e @danielGalvao ?

Foquem por enquanto em apenas inserir o botão de Inscrever lá em cima, vamos dividir por partes, beleza?

Vou transformar cada item num checkbox no inicio dessa issue

**Comment by soutot** [comment]
Pessoal, estava conversando aqui com amigos e todos nós ficamos com a mesma sensação de que o azul claro como background ficou um pouco estranho. A cor está bem forte e talvez fique um pouco "cansativo" para leitura.
Gostaria de deixar essa sugestão de utilizar uma cor mais neutra nos backgrounds e manter o azul claro apenas para detalhes do texto.

**Comment by danvitoriano** [comment]
legal @soutot se o pessoal conseguir fazer essas mudanças no arquivo XD, manda bala e posta aqui pra gente! vamos mexendo a varias mãos!

**Comment by danvitoriano** [comment]
@danielGalvao e @rodrigooler quem pode inserir o botão de venda de ingressos right now no site?

`<a class="button-small-text" href="https://www.sympla.com.br/react-conf-brasil-2017__161239" target="_blank"><img src="http://www.sympla.com.br/images/btn-register se.png" alt="" style="" /></a>`

**Comment by danvitoriano** [comment]
movida pra issue https://github.com/react-brasil/conf/issues/36
