### ISSUE TITLE
Definir LineUp do evento

### ISSUE THREAD

**Issue by keuller** [react-brasil/reactconfbr#2]
Precisamos definir quais palestras teremos no evento, levando em consideração 1 dia de evento, contendo 8 palestras de 50 minutos.

**Comment by WennderSantos** [comment]
Poderia ser usado um modelo de submissão, o http://call4paperz.com/ pode ajudar. Inclusive, a submissões podem receber votos. 
É uma forma democrática para definir as apresentações :)
O que acham?

**Comment by albertossilva** [comment]
@WennderSantos Acredito que seja legal sim o call4paperz, mas podemos também convidar alguns palestrantes, digo... maioria das palestras seria por voto, e algumas seriam por convite.

**Comment by felipedaraujo** [comment]
O call for paper já está aberto? Onde está o link?

**Comment by sebas5384** [comment]
@felipedaraujo estamos nisso! em breve sai o link 👍

**Comment by danvitoriano** [comment]
Call 4 Papers aberto!
https://www.papercall.io/reactconfbr

Por enquanto o formato sera de 1 keynote para o primeiro patrocinador Senior e mais 7 slots!
