### ISSUE TITLE
React Conf Brasil 2018 - Slides, vídeos e materiais das talks

### ISSUE THREAD

**Issue by lucianomlima** [react-brasil/reactconfbr#23]
Deixe abaixo o link para o slide/vídeo ou qualquer outro material relevante da sua talk!

Para quem não foi speaker, por favor, evite comentários para deixarmos essa issue mais objetiva

**Comment by sibelius** [comment]
https://twitter.com/sseraphini/status/1053952751418441728

**Comment by brunodahora** [comment]
Slides da Palestra: "Otimize seu bundle com Webpack 4 e Create React App"
http://bit.ly/react_conf_brunodahora

**Comment by raphaelpor** [comment]
**Talk**: "A jornada do React Native na Globo.com"
https://speakerdeck.com/raphaelpor/a-jornada-do-react-native-na-globo-dot-com

**Comment by gvarandas** [comment]
**React-Native: Como economizamos 1500 horas por Projeto**
_(Ou como deveria ter se chamado: Microfrontends com React-Native)_
https://www.icloud.com/keynote/0zIJ9Nrzh5ELy-X1ZuzaJKKoQ#ReactConfBR_-_GAM

**Comment by fdaciuk** [comment]
[**The powers of SSR**](https://docs.google.com/presentation/d/1lY5u-TeYDVdg4rfd5uWub2EYC8QHNqbvnbtYOIQg_qs/present)

**Comment by mtmr0x** [comment]
https://www.icloud.com/keynote/0LZmoTka2s8xuTKJsEkUrniBA#happy-and-long-life-with-state-containers-pt

**Comment by renatobenks** [comment]
https://speakerdeck.com/renatobenks/modeling-graphql-apis

**Comment by hugobessaa** [comment]
*Mantendo Webapps em produção, sem dor de cabeça*
https://speakerdeck.com/hugobessaa/mantendo-webapps-em-producao-sem-dor-de-cabeca

**Comment by nicholasess** [comment]
[Como escalar projetos React com monorepo](https://docs.google.com/presentation/d/1jzNwlew9qy9czg34PCOy3z4lKw4KofLZSnbHulXe9E0/edit?usp=sharing)

**Comment by danielGalvao** [comment]
@olarclara @haskellcamargo  @raphamorim @jaburcodes @pedronauck

**Comment by pedronauck** [comment]
https://speakerdeck.com/pedronauck/reactconf-2018-presenting-docz

**Comment by olarclara** [comment]
https://speakerdeck.com/olarclara/react-nas-trincheiras

**Comment by raphamorim** [comment]
link dos slides: https://speakerdeck.com/raphamorim/writing-your-own-react-renderer

links das demos:
http://raphamorim.io/react-song/?s=backstreetboys
http://raphamorim.io/react-song/?s=yuyuhakusho
http://raphamorim.io/react-song/?s=beverlyhillscop

**Comment by AndreAntunesVieira** [comment]
Só pra deixar organizado tudo e adicionar as duas que estão faltando (mesma ordem prevista no [site](http://reactconfbr.com.br)):
- [ReasonML Taken Seriously](https://slides.com/marcelocamargo/react-conf-2018-reasonml#/)
- [Docz: de 0 a 5.000 ⭐️ em 2 semanas](https://speakerdeck.com/pedronauck/reactconf-2018-presenting-docz)
- [React-Native: Como economizamos 1500 horas por Projeto
(Ou como deveria ter se chamado: Microfrontends com React-Native)](https://www.icloud.com/keynote/0zIJ9Nrzh5ELy-X1ZuzaJKKoQ#ReactConfBR_-_GAM)
- [Otimize seu bundle com Webpack 4 e Create React App](http://bit.ly/react_conf_brunodahora)

- [React nas trincheiras](https://speakerdeck.com/olarclara/react-nas-trincheiras)
- [Como escalar projetos React com monorepo](https://docs.google.com/presentation/d/1jzNwlew9qy9czg34PCOy3z4lKw4KofLZSnbHulXe9E0/edit)
- [TypeScript vs Flow no segundo semestre de 2018](https://slides.com/larissathaisdefarias/typescript-vs-flow)
- [Escrevendo seu próprio React Render](https://speakerdeck.com/raphamorim/writing-your-own-react-renderer)

- [A jornada do React Native na Globo.com](https://speakerdeck.com/raphaelpor/a-jornada-do-react-native-na-globo-dot-com)
- [Mantendo Webapps em produção, sem dor de cabeça](https://speakerdeck.com/hugobessaa/mantendo-webapps-em-producao-sem-dor-de-cabeca)
- [Animações em React Native](https://docs.google.com/presentation/d/1DwgfZ5aIxKnVIHEdUkZNxRgI3tlR80zdg7C2EC3Dqig/edit?usp=sharing)
- [Uma experiência open-source com React Native, GraphQL e Relay Modern](https://docs.google.com/presentation/d/1yBmaSl9aN8i6a5EpNGg7W9FiTgRBFScMx1KmxXaJZ8I/edit?ouid=105428684115126924364&usp=slides_home&ths=true)

- [Modeling GraphQL APIs](https://speakerdeck.com/renatobenks/modeling-graphql-apis)
- [The powers of SSR](https://docs.google.com/presentation/d/1lY5u-TeYDVdg4rfd5uWub2EYC8QHNqbvnbtYOIQg_qs/present)
- [The Frontend Dichotomy](https://speakerdeck.com/sibelius/the-frontend-dichotomy)
- [Meu próprio conjunto de regras para viver uma vida longa com state containers](https://www.icloud.com/keynote/0LZmoTka2s8xuTKJsEkUrniBA#happy-and-long-life-with-state-containers-pt)

**Comment by lucianomlima** [comment]
Show!
