### ISSUE TITLE
Comitê de Organização

### ISSUE THREAD

**Issue by aureliosaraiva** [react-brasil/reactconfbr#4]
Galera, como muitas já ficaram sabendo pelo Slack da comunidade ReactJS Brasil. Estamos iniciando o planejamento da organização do ReactConf Brasil para esse ano.

O objetivo dessa issue é que outras pessoas possam se disponibilizar para participar do comitê de organização. Como todos sabem, organizar um evento não é fácil, então precisamos de todo o apoio, seja ele operacional,  ideias, indicação de patrocínio, etc.

Como a premissa é um evento orientado pela comunidade e esses digamos cabeças iram ajudar a concluir as metas e sugestões de todos para que possamos tirar do papel o ReactConf Brasil esse ano ainda.

## **[Comitê de Organização](https://github.com/react-brasil/reactconfbr/issues/4#issuecomment-272578961)**

**Organização geral / Coordenação**
Responsável: @aureliosaraiva

**Brand / Material gráfico**
Responsável: @henriquesosa 
Equipe: @henriquesosa / @nic

**Landing Page / Site**
Responsável: @lucasbento (Dono) / @henriquesosa / @nic
Equipe: @lucasbento / @henriquesosa / @nic / @alvarowolfx

**Palestrantes / Grade de programação**
Responsável: @sebas5384 
Equipe: @sibelius

**Marketing / Divulgação**
Responsável: Em aberto
Equipe: @femontanha / @fervassoler / @danvitoriano

**Captação de patrocínio**
Responsável: @aureliosaraiva (Até alguém querer assumir, rsrs)
Equipe: Todos

**Comment by danvitoriano** [comment]
Primeiro, parabéns pela iniciativa.
Posso ajudar com organização, divulgação, operacional. Moro em São Paulo capital, mas há um ano atrás ajudei a trazer o FEMUG pra região do ABC :)

**Comment by thiagoterleski** [comment]
Eu posso ajudar de alguma maneira, estou em Curitiba, posso ajudar na parte de divulgação (site e outros meios)

**Comment by vinicius-sabadim** [comment]
Eu posso ver se consigo patrocínio com a empresa que eu trabalho. Eles estão na moda do React.

**Comment by aureliosaraiva** [comment]
Existem algumas frente que precisam de dono galera!

**Divulgação**
**Material gráfico/site**
**Capitação de patrocínio**
**Auditoria do financeiro**  Para ajudar a controlar os números do evento
**Programação**: mais do que fechar a programação, fazer a logística dos palestrantes (hotel, viagem, etc).

**Comment by henriquejensen** [comment]
Eu trabalho com React aqui em Campinas, se eu puder ajudar com alguma coisa

**Comment by sebas5384** [comment]
Massa! parabéns aos que estão puxando pra frente 👍 

**Eu posso ajudar em:**
1. Na organização das propostas de palestras ou keynotes (já fiz antes em outros eventos).
2. Ver patrocínio da [Taller](taller.net.br).
3. Voluntário na operação do evento.
4. Divulgação do evento.

Seria interessante definir um hangout para começar algum trello, e colocar os chairman / responsáveis / líderes das áreas.

**Comment by sebas5384** [comment]
Ah!! uma coisa MUITO importante, precisamos procurar mulheres, diversidade é importantíssimo!!

**Comment by dleitee** [comment]
Primeiramente, parabéns pela iniciativa.

Segundamente, posso ajudar da seguinte maneira:

1. Ver patrocínico com a [Cheesecake Labs](https://www.ckl.io/).
2. Ajudar com o site e divulgação.

**Comment by joaolucasl** [comment]
\õ/

Posso ajudar:
1. Na organização do evento
2. Staff _durante_ o evento
3. Conversar com a empresa onde trabalho (Pagar.me) pra patrocinar no evento!

**Comment by guilhermedecampo** [comment]
[Astrocoders](https://astrocoders.com) pode ajudar com:

1. Patrocínio da cerveja
2. Staff

**Comment by femontanha** [comment]
O <a href="http://devnaestrada.com.br">DEVNAESTRADA</a> pode ajudar a divulgar o evento, trabalho na mesma empresa que o @vinicius-sabadim e também posso ajudar a tentar o patrocínio com ela.

**Comment by nic** [comment]
Estamos a disposição!

@nic (eu)
- Material gráfico
- Landingpage
- Divulgação
- Staff

@fervassoler (minha esposa)
- Auditoria do financeiro
- Staff

**Comment by danvitoriano** [comment]
@aureliosaraiva posso ajudar na criação de materiais e textos para organização e divulgação do evento, como apresentações explicando as cotas de patrocínio, criação e revisão de texto do site (eu faço revisão dos posts do Tableless), criação de um código de conduta, apresentação para palestrantes, enfim, material gráfico e multimídia.

**Comment by henriquesosa** [comment]
@nic Eu quero ajudar com o Material Grafico e a Landing Page ;). Além claro, irei participar como staff

**Comment by AnnaNee** [comment]
Opa, eu posso ajudar nos seguintes:

- Staff
- Landing Page
- Captar patrocínio da empresa onde trabalho
- Captar divulgação e apoio em canais de inclusão de mulheres em TI (Rails Girls, Programaria, Reprograma)

**Comment by torto** [comment]
Moro em São Paulo sendo assim tudo que precisarem de tempo e disposição de minha pessoa para fazer os corres estou aqui para isso!
❤️ 👯

**Comment by albertossilva** [comment]
Eae galera, nós aqui da [Sprinklr BR](https://www.sprinklr.com/)/[Scup](http://www.scup.com/), podemos ajudar também:

- Staff durante evento
- Landing Page
- Divulgação
- Patrocínio
- Apoiar os palestrantes (ajudar com logística também)

E viva o React.

**Comment by marcelorl** [comment]
To em SP, posso ajudar no que for preciso.

**Comment by thiagovigliar** [comment]
Compartilhei aqui na Concrete Solutions!

To em SP e posso ajudá-los tb!!!

**Comment by aureliosaraiva** [comment]
Galera, segue o comitê de organização, está dividido por temática alguns head de cada temática ainda estão em aberto.

- Organização geral / Coordenação
-- Responsável: @aureliosaraiva

**Comment by Kirmayrtomaz** [comment]
Posso ajudar também, 

1. Posso ver o patrocínio aqui na Concrete Solutions onde trabalho
2. Ajudar com a Landing 
3. Staff 
4. Divulgação

**Comment by RodrigoOler** [comment]
Posso ajudar também,

1. Posso ver o patrocínio
2. Ajudar com a Landing
3. Staff
4. Divulgação

**Comment by aureliosaraiva** [comment]
@RodrigoOler está rodando uma outra issue sobre brand, se quiser acompanhar. O objetivo é definir pra começar a trabalhar na landing page.

https://github.com/react-brasil/reactconfbr/issues/5

**Comment by PatriciaMagi** [comment]
Oi @aureliosaraiva , boa noite. Amanhã tem como a reunião com o Kevin ser na parte da manhã? 9h?Participará eu, o diretor de minha unidade, o Kevin e o Wendel. 

Fico no aguardo!

**Comment by danvitoriano** [comment]
Por enquanto o Comite de Organizacao eh:

@danvitoriano
@sibelius 
@sebas5384 
@nic 
@ronal2do 

Se tiver interesse em participar das negociações com fornecedores, fechar parcerias, patrocinadores, e entrar para a famosa planilha CU DE UM ( porque se der algum problema, vai cair no cu de um aqui rs) manda um e-mail para reactconfbr@gmail.com pfv!
