### ISSUE TITLE
Branding

### ISSUE THREAD

**Issue by danvitoriano** [react-brasil/reactconfbr#5]
Discuss trademark, branding, stationery and ID guide.

**Comment by lucasbento** [comment]
@danvitoriano: dei merge no seu PR, acho que agora você tem acesso de write no repo.

Temos dois logos agora no branch `logo`: https://github.com/react-brasil/reactconfbr/tree/logo/branding/assets

o que acham, @react-brasil/conf?

**Comment by danvitoriano** [comment]
quer mudar os logos pra uma branch separada @lucasbento ?

**Comment by danvitoriano** [comment]
ah, vc ja fez isso! :)

**Comment by she-dev** [comment]
Ficou muito bom, parabéns! Eu gostei mais do op2

**Comment by gilbarbara** [comment]
Como ficaria com o fundo branco?
E seria legal ter uma opção em SVG sem fundo nenhum

**Comment by brunolemos** [comment]
Tem o psd deste logo pra gente iterar em cima?

**Comment by danvitoriano** [comment]
Galera, não tenho o PSD.
Eu fiz isso no GIMP! Dei print screen em umas fontes que eu curti no dafont.com e fui montando. Posso providenciar uma versão em fundo branco.
Posso passar também o arquivo .xcf, que é o "psd" do gimp.

**Comment by danvitoriano** [comment]
Lembrando que... isso são sketchs. Se forem escolhidos, tem que ser arte finalizados. Eu já fiz algo pensando na facilidade de usar em SVG, mas isso são apenas esboços, estão meio tortos aliás. Alguém teria que fazer a arte final, deixar tudo proporcional, fazer as variações, aplicações monocromáticas, formatos vertical, horizontal. Vcs querem ver outras opções dessa mesma versão? Mas da 1 ou da 2?

**Comment by danvitoriano** [comment]
Versão fundo branco na Issue @brunolemos @gilbarbara @lucasbento :)

**Comment by sebas5384** [comment]
Massa! gostei!.
Eu tenho algumas dúvidas sobre a aplicabilidade do logo, pois transparência sempre é difícil de utilizar em outras escalas, ou monocromático.

**Comment by danvitoriano** [comment]
Vou fazer a versão monocromática @sebas5384 
Consegui salvar em PSD @brunolemos:
https://github.com/react-brasil/reactconfbr/tree/logo/branding/psd

**Comment by italomen** [comment]
Fiz umas sugestões aqui para mostrar outras possibilidades. :)

![captura de tela 2017-01-26 as 11 09 05](https://cloud.githubusercontent.com/assets/8739899/22333325/bcb61080-e3bc-11e6-8661-beb6273759f5.png)

**Comment by danvitoriano** [comment]
Opções monocromáticas e aplicação em fundo negativo adicionadas à issue @sebas5384

**Comment by sebas5384** [comment]
massa @danvitoriano ta ficando show 👍

**Comment by danvitoriano** [comment]
versões verticais adicionadas

**Comment by lhguerra** [comment]
Sugestão baseada no trabalho feito até agora e nos 2 cents do @italomen: fazer uma só versão do logotipo, fazendo com que a única diferença entre horizontal e vertical seja a posição do símbolo. Isso dá mais pregnância pra forma da marca gráfica.

Outra coisa seria não usar transparências, porque dificulta muito pra ter unidade nas aplicações e pode encarecer os materias gráficos.

**Comment by danvitoriano** [comment]
Oi @lhguerra não estamos usando transparência, são apenas variações e sobreposições de cores :)

**Comment by lucasbento** [comment]
![image](https://cloud.githubusercontent.com/assets/6207220/22345406/1b2a24ba-e3e7-11e6-87b3-616f4e584238.png)

Logotipo da [ReactConf](http://conf.reactjs.org) do FB.

**Comment by danvitoriano** [comment]
pow, a cor dos q eu fiz tá meio fora da cor do React kkk

**Comment by liviamorim** [comment]
Curti mais a sugestão do @italomen. (:
Pensar muito em shade/transparência ferra a aplicação no material impresso e nas camisetas.

**Comment by PatriciaMagi** [comment]
Existe um material desenvolvido por uma equipe aqui do SENAI. Caso precisem, estamos por aqui! (11) 3273-5165 e/ou pmagi@sp.senai.br.


**Vídeos**

_UpLab_
https://vimeo.com/201293312

_E.cub_
https://vimeo.com/201287294

_Desenvolvedor Multiplataforma_
https://vimeo.com/201294077

Sasasaki
https://vimeo.com/201292496

**Comment by lucasbento** [comment]
Pessoal, a gente já passou por isso com o logo da comunidade do React Brasil e o @nic mandou bem fazendo esse:
![image](https://cloud.githubusercontent.com/assets/6207220/22396205/6505c1b2-e53a-11e6-8498-3bd917553a21.png)

Eu acho ele bem legal, poderíamos mudar algumas coisas (como colocar React Brasil Conf, etc) e melhorá-lo caso seja preciso, o que acham?

**Comment by danvitoriano** [comment]
enquanto ninguém decide eu vou sugerindo opções.
esta eu fiz mais parecido com a logo do React Brasil, tô usando a fonte que está no site do React, a Proxxima.

![reactconf-op-mais-parecida-com-o-logo-da-react-brasil](https://raw.githubusercontent.com/react-brasil/reactconfbr/544beff04c7940ddcf290ca4a4496e5adaa174de/branding/assets/react-conf-br-op76253.png)

**Comment by danvitoriano** [comment]
![reactconf-op-mais-parecida-com-o-logo-da-react-brasil](https://raw.githubusercontent.com/react-brasil/reactconfbr/1e5c06d3f49084f42a5c98c7d2f09a10f8807250/branding/assets/react-conf-br-op76254.png)

**Comment by kevindantas** [comment]
Eae pessoal!

Aqui no SENAI temos um time de design que desenvolveu uma proposta de identidade visual para o evento. 
Como estratégia visual utilizamos uma logo cambiante, onde a proposta é utilizar variações e mutações no design, simbolizando a troca de experiência, networking, integração entre as pessoas no evento. 

![react_conf_br](https://cloud.githubusercontent.com/assets/3884633/22480350/42c3b17c-e7d8-11e6-9d42-84cbb76da0e9.gif)

Segue como ficaria a aplicação da identidade visual em algumas peças.

![banner](https://cloud.githubusercontent.com/assets/3884633/22480379/572137ac-e7d8-11e6-81f9-9c57ef5fb6d5.jpg)
![camiseta1](https://cloud.githubusercontent.com/assets/3884633/22480383/57298812-e7d8-11e6-8d9a-618569fbf6aa.jpg)
![camiseta2](https://cloud.githubusercontent.com/assets/3884633/22480380/57226f6e-e7d8-11e6-86fd-0e7c9b1466ae.jpg)
![cartaz](https://cloud.githubusercontent.com/assets/3884633/22480381/57239ef2-e7d8-11e6-8d1f-3ca8ee3c3035.jpg)
![sacola](https://cloud.githubusercontent.com/assets/3884633/22480382/5727ca40-e7d8-11e6-8731-181dfda29b01.jpg)

O que vocês acham?

**Comment by lucasbento** [comment]
Caramba, mandaram muito bem, @kevindantas!

Não sei bem dizer sobre essa ideia do logo se alterando (mutability is not good) mas gostei **muito** desse último que tá na sacola, ficou muito bom mesmo!

cc @ronal2do, @react-brasil/conf.

**Comment by gilbarbara** [comment]
@kevindantas Ficou bem legal, parabéns. Eu curti a animação! 👍

**Comment by henriquesosa** [comment]
@kevindantas Se ninguém discordar, pra mim é aprovado!

**Comment by kevindantas** [comment]
@lucasbento a mutabilidade tem que ficar longe do JS mesmo hahaha

A nossa ideia com essas mutações é poder usar a mesma logo de vários jeitos diferentes, parecido com o que a MTV, Google e outros caras fazem com a logo deles.

![google](https://cloud.githubusercontent.com/assets/3884633/22490700/d0553b0a-e805-11e6-8ed5-8876ca58bd6e.jpg)

A gente estava até pensando em usar as variações da logo nos brindes, igual o que a gente fez nas camisetas, daí os brindes do evento podem ser colecionáveis.

**Comment by sebas5384** [comment]
@kevindantas ficou muito bom!! por mim ta aprovado tmb!

**Comment by kevindantas** [comment]
Pessoal, também acho legal a gente já pensar em quais peças nós vamos fazer para evento.

Eu pensei em fazer:
- Banner
- Cartaz
- Totem
- Camisetas
- Adesivos
- Botton (talvez)

O que mais vocês acham que a gente poderia ter no evento?

**Comment by camilapferreira** [comment]
@kevindantas Eu curti!

**Comment by nic** [comment]
@lucasbento Considero importante o branding trazer a ideia que:
- (1) de forma macro: se trata de Brasil (e o logo do React Brasil já resolve esta questão)
- (2) de forma micro: se trata de Florianópolis.

Seguindo este conceito, sugiro caminharmos neste sentido:

![captura de tela 2017-02-06 as 02 49 46](https://cloud.githubusercontent.com/assets/66042/22635063/0b51bf02-ec17-11e6-8b18-4e2f26aa7903.jpg)

**Comment by aureliosaraiva** [comment]
@kevindantas ficou muito bom mesmo o trabalho realizado por vocês.

@nic gostei bastante da proposta de seguir essa linha temática.

Acredito que podemos unificar as propostas de vocês e termos algo fantástico.

Minha ideia é marcar um hangout ainda essa semana para fechar esses itens e começar a trabalhar em landing page.

cc: @henriquesosa / @nic 

Vamos conversando e alinhado o melhor horário no Slack.

**Comment by danvitoriano** [comment]
Fala galera!

@aureliosaraiva Estamos conseguindo alinhar várias coisas no Slack, dando andamento nessa parte da identidade visual da Conf e futuramente a criação da landing page. Vou puxar o @kevindantas para discutirmos mais a respeito da proposta que ele nos passou e fazer um mix com a ideia do @nic. Vamos posicionando a galera aqui tb. :)

**Comment by aureliosaraiva** [comment]
@danvitoriano perfeito, conversei agora a pouco com a @PatriciaMagi.

**Comment by danvitoriano** [comment]
bacana @aureliosaraiva! 
depois me posiciona pra eu não abrir threads de coisas que já foram conversadas! :relaxed:

**Comment by PatriciaMagi** [comment]
Oi @aureliosaraiva , deixei um recado para você no slack. Amanhã das 8:00 às 9:00 está okay. Se possível me passe o seu telefone, assim fica melhor. Um abraço.

**Comment by PatriciaMagi** [comment]
Oi @danvitoriano , tudo bem? O Núcleo de TI do Senai está a disposição. Só precisamos alinhar com vocês como será a parte de parceria, data, o que já temos e o que é necessário para que possamos nos organizar. O SENAI tem interesse em disponibilizar o @kevindantas para palestrar também. :) 

O meu contato é (11) 3273-5165 e pmagi@sp.senai.br

Fico a disposição!

**Comment by danvitoriano** [comment]
Oi @PatriciaMagi! Estavámos discutindo com @kevindantas no Slack sobre a questão do logo e o que mais o Senai poderia nos ajudar. Mandei uma mensagem, mas ele estaria ocupado agora a tarde, e disse que conversaria com a gente mais a noite. Vou incluir você na thread. :relaxed:

**Comment by lucasbento** [comment]
@PatriciaMagi, @kevindantas: estamos aguardando a resposta de vocês no nosso Slack à alguns dias, temos algum progresso sobre o desenvolvimento da marca e da landing page?

cc @danvitoriano.

**Comment by ronal2do** [comment]
Tbm aguando para dar sequencia ao desenvolvimento.

**Comment by danvitoriano** [comment]
O @ronal2do ficou de ajudar com a landing, mas isso depois que a gente tivesse finalizado o logo. O @henriquesosa talvez possa ajudar com a landing tb, fiquei sabendo q ele já tinha algo meio que começado. :)

**Comment by PatriciaMagi** [comment]
Olá @danvitoriano , @lucasbento e @aureliosaraiva  , tudo bem?  Vamos marcar um skype no dia 20/02 às 09:00? 
Wendel Nascimento: wendel.nascimento2@outlook.com
Kevin Dantas Shih: kevin.ds.29
Patricia Magi: patriciamagi

Objetivo: Utilização da identidade criada pelo Senai, participação de nosso especialista no evento. 

Um abraço.

**Comment by danvitoriano** [comment]
Combinado @PatriciaMagi estarei online no dia! Obrigado!

**Comment by danvitoriano** [comment]
@PatriciaMagi @lucasbento @aureliosaraiva @kevindantas meu skype é danilo.vitoriano

**Comment by danvitoriano** [comment]
Identidade visual criada com sucesso. :1st_place_medal: 
Valeu a todos que se envolverão, mandaram opções, participaram, opinaram.
Em breve ela estará circulando por aí!
