### ISSUE TITLE
Pesquisa sobre temas de palestras do React Conf BR

### ISSUE THREAD

**Issue by sibelius** [react-brasil/reactconfbr#8]
Quais temas vocês gostariam de ver nas palestras no React Conf BR?

Comente nessa issue com o tema que você gostaria que fosse abordado.

Participem do react brasil slack (http://react-brasil-slack.herokuapp.com/)

votem com 👍  se gostarem de alguém tema já proposto, ou postem um novo tema se ainda não existir

**Comment by Kirmayrtomaz** [comment]
Arquitetura de projetos react + redux

**Comment by dleitee** [comment]
CSS Modules

**Comment by dleitee** [comment]
Server Side Rendering

**Comment by dleitee** [comment]
Redux Asynchronous

**Comment by sibelius** [comment]
Relay

**Comment by sibelius** [comment]
Fiber

**Comment by sibelius** [comment]
React Native

**Comment by marquinhoalm** [comment]
Uma de React Native Basic e uma Advanced pra pegar todos os publicos :)

**Comment by felipedaraujo** [comment]
Role-based authorization

**Comment by felipedaraujo** [comment]
Push Notification on React Native

**Comment by felippepuhle** [comment]
Eu gosto bastante daquelas palestras no formato 'caso de sucesso', com explicações da arquitetura do projeto trabalhado e o por quê cada escolha foi tomada 😄

**Comment by soutot** [comment]
Styling and Animation on React Native

**Comment by soutot** [comment]
Performance improvement on React Native

**Comment by sibelius** [comment]
RelaySubscriptions

**Comment by sibelius** [comment]
Redux

**Comment by sibelius** [comment]
MobX

**Comment by sibelius** [comment]
Universal apps - almost same code on web and o app

**Comment by sibelius** [comment]
Como migrar códigos legados para React

**Comment by sebas5384** [comment]
GraphQL com [Apollo Stack](https://github.com/apollographql)

**Comment by RodrigoOler** [comment]
React Native + Firebase

**Comment by RodrigoOler** [comment]
Optimising React Native: Tools and Tips

**Comment by RodrigoOler** [comment]
RxJS + Redux + React

**Comment by RodrigoOler** [comment]
React Best Practices for Reusable UI Components

**Comment by RodrigoOler** [comment]
React & Flow

**Comment by RodrigoOler** [comment]
Scaling React Applications

**Comment by RodrigoOler** [comment]
React for TV UIs

**Comment by she-dev** [comment]
GameDev com React/React Native

**Comment by she-dev** [comment]
TDD com React

**Comment by vagnerasilva** [comment]
TDD com react

**Comment by ronal2do** [comment]
Living Code - Integrando Relay ao RN.

**Comment by danvitoriano** [comment]
Progressive Web Apps com React + Redux

**Comment by soutot** [comment]
React Native + Realm

**Comment by soutot** [comment]
ReactVR

**Comment by soutot** [comment]
React Native Touch & Gesture

**Comment by AgtLucas** [comment]
React Native Navigation Hell.

**Comment by soutot** [comment]
React Native offline-first

**Comment by AgtLucas** [comment]
styled-components (e outras soluções css-in-js).

**Comment by henriquejensen** [comment]
Promises e Redux

**Comment by henriquejensen** [comment]
Webpack, Performance Apps React

**Comment by enieber** [comment]
Testes automatizado

**Comment by ronal2do** [comment]
Relay and GraphQL

**Comment by ramirio** [comment]
omcljs

**Comment by EmersonStark** [comment]
React Native

**Comment by AgtLucas** [comment]
Reason.

**Comment by fdaciuk** [comment]
PWA com React

**Comment by danvitoriano** [comment]
@fdaciuk tb to bem curioso com esse assunto cara, to pesquisando e achando algumas coisas bem interessantes

**Comment by alvarowolfx** [comment]
@danvitoriano eu fiz o site Poketrainers.co com conceitos de PWA e React, se quiser dar uma olhada https://github.com/alvarowolfx/poketrainers

**Comment by sibelius** [comment]
galera vamos deixar essa issue só para temas/tópicos da react conf brazil, divulguem outras coisas no react brasil slack http://react-brasil-slack.herokuapp.com/

votem com 👍  se gostarem de alguém tema já proposto, ou postem um novo tema se ainda não existir

**Comment by HectorIFC** [comment]
High order components usando middlewares do redux com async e await

**Comment by HectorIFC** [comment]
React e Relay.

**Comment by fdaciuk** [comment]
Alternativas ao React: Preact, Inferno.js, etc

**Comment by fdaciuk** [comment]
React Router v4

**Comment by fdaciuk** [comment]
Novidades do webpack 2

**Comment by sibelius** [comment]
React Navigation (web, react native, hybrid)

**Comment by fdaciuk** [comment]
SSR com outras linguagens além do Node

**Comment by fdaciuk** [comment]
Trabalhando com imutabilidade (sem libs e/ou com libs como Immutable, Ramda, etc)

**Comment by yanmagale** [comment]
Arquitetura de aplicações react com redux e interação com API/Servidor

**Comment by brunolemos** [comment]
Realtime apps with Redux

**Comment by brunolemos** [comment]
Realm + Redux

**Comment by brunolemos** [comment]
CodePush (ou outra alternativa de over the air update)

**Comment by brunolemos** [comment]
Dicas na pegada de deploy bot, git hooks, lint/prettier, automatização de tarefas repetitivas, etc

**Comment by albertossilva** [comment]
Keep UI under React, move complexity to models
https://www.papercall.io/speakers/albertossilva/speaker_talks/38422-keep-ui-under-react-move-complexity-to-models

**Comment by danvitoriano** [comment]
Essa talk foi submetida no nosso call 4 papers @albertossilva ?

**Comment by albertossilva** [comment]
@danvitoriano, foi sim.

**Comment by danvitoriano** [comment]
bacana, vamos deixar aqui então só pros temas, pq se todo mundo começar a fazer isso aí já viu né rs

**Comment by gabrielferreiraa** [comment]
PWA com React seria incrível. Best Practices de todo workflow react seria legal também :D #ansioso

**Comment by grsabreu** [comment]
State and styling HoCs, going beyond data fetching containers!

https://www.papercall.io/speakers/15856/speaker_talks/38510-composable-and-styling-components-going-beyond-data-containers
